const site = {
  baseUrl: 'https://www.gael-lebellec.bzh',
  title: 'Gaël Le Bellec',
  description: '',
  home: {
    fr: {
      title: 'x3 Champion du Monde de Duathlon',
      description: 'Suivez sa saison 2019, son calendrier, ses actus et ses résultats.',
      version: 'fr',
      cta: 'Ma Newsletter',
      cta_description:
        'Abonnez-vous maintenant et restez informé chaque mois de mes prochaines compétitions, mes derniers classements et surtout mon défrief du mois!',
    },
    en: {
      title: 'x3 Duathlon World Champion',
      description: 'Follow his 2019 season, his calendar, his news and his results.',
      version: 'en',
      cta: 'My Newsletter',
      cta_description:
        'Sign up now and stay informed each month of my future races, my last results and my monthly debrief!',
    },
  },
  header: {
    news: {
      fr: 'Actus',
      en: 'News',
    },
    calendar: {
      fr: 'Calendrier',
      en: 'Calendar',
    },
    results: {
      fr: 'Resultats',
      en: 'Results',
    },
    bio: {
      fr: 'Bio',
      en: 'Bio',
    },
    sponsors: {
      fr: 'Sponsors',
      en: 'Sponsors',
    },
    mentoring: {
      fr: 'Parrainage',
      en: 'Mentoring',
    },
    team: {
      fr: 'Clubs',
      en: 'Teams',
    },
    flag: {
      fr: 'en.png',
      en: 'fr.png',
    },
    see_more: {
      fr: 'Voir +',
      en: 'See +',
    },
  },
  mentoring: [
    { name: 'lycée kerlebost', img: '/img/g872.png' },
    { name: 'la gourinoise contre le cancer', img: '/img/g878.png' },
    { name: 'la littorale 56', img: '/img/g897.png' },
    { name: 'TKB', img: '/img/g905.png' },
    { name: 'triathlon tramelan', img: '/img/rect4237.png' },
  ],
  profil: {
    fr: {
      name: 'Nom',
      nationality: 'Nationalité',
      date_of_birth: 'Date de naissnace',
      size: 'Taille',
      weight: 'Poids',
      awards: 'Palmarès',
      results: [
        'Champion du Monde longue distance 2014, 2015 et 2018',
        'Vainqueur Powerman Florides 2016',
        'Vainqueur Powerman Philippines 2016',
        'Vainqueur du Powerman Luxembourg 2015',
        '2ème du Powerman St Wendel 2016',
        '2ème du Powerman Luxembourg 2016',
        '3ème du Powerman Malaisie 2016',
        'Champion de France Longue distance 2014',
        'Champion de France par équipe 2015 (d1)',
        'Champion de Bretagne Courte distance 2014',
      ],
      bio: [
        'Gaël Le Bellec est né le 6 avril 1988 à Entrechaux, dans le Vaucluse, d’un père breton et d’une mère anglaise. C’est sur les pentes du Mont Ventoux, ce fameux géant de Provence, qu’il retourne s’entraîner quand il revient sur ses terres natales. Dès son plus jeune âge, il partait courir seul sur les chemins de Provence. La passion du sport était déjà là…',
        'Il s’illustre dès 12 ans sur les cross nationaux et courses locales qu’il remporte pour la plupart. Quand il vient habiter en Bretagne avec ses parents, il change de discipline pour le cyclisme. Sa première licence à 13 ans et une progression régulière l’amène en équipe de France juniors où il côtoiera de grands coureurs actuels (Tony Gallopin, Arthur Vichot…). Repéré pour ses qualités physiques à 17 ans il intégrera le pôle France de Bordeaux-Talence où il roulera aux côtés de grands noms du cyclisme sur route et piste (Mathieu Ladagnous, Vivien Brisse…). Il passera ensuite 2 années dans le club de Côtes d’Armor Cyclisme où il est aujourd’hui toujours licencié avant de signer en 2011 dans l’équipe professionnelle Raleigh où il évoluera au niveau continental. Cette aventure en terre britannique, pays de ses origines, sera une belle et riche expérience pendant laquelle il côtoiera des athlètes avec des cultures et des visions du sport très intéressantes. L’approche anglo-saxonne de la  compétition et son  côté fun, relax, lui permettent aujourd’hui de relativiser et de donner au sport sa juste place dans sa vie.',
        'Il décidera ensuite de rendre au cyclisme ce que celui-ci lui a apporté, en devenant entraîneur de la ligue de Bretagne de cyclisme au sein de laquelle il coache les juniors et les féminines. C’est alors qu’au contact de ces jeunes sportives et sportifs il ressent le besoin d’un nouveau challenge. Il décide alors de reprendre doucement la course à pied en 2013 dans l’équipe de Marie-Pierre Toudret-Duros, l’UA Langueux. Il rechausse les pointes lors de l’hiver suivant et remporte le titre départemental de cross puis enchaîne les bons résultats. Il décide l’année suivante de tenter l’aventure en duathlon au sein du club de Pontivy. Cette année-là, après avoir remporté le titre régional et le titre national coup sur coup, il décide de s’engager sur la légendaire épreuve de Zofingen que des grands noms tels que Mark Allen ont remporté. C’est ainsi que sur le 3ème duathlon de sa carrière, il devient, en Suisse, le premier Français à inscrire son nom au palmarès du Powerman de Zofingen au terme des 10km à pied, 150 à vélo et 30km à pied.Une nouvelle carrière dans cette discipline du triple effort s’ouvre à lui. Ses débuts très prometteurs et ses performances sont une réelle surprise dans le milieu, et font de lui la nouvelle sensation du duathlon. La saison 2015 s’annonce riche en sensations pour celui qui rejoint les rangs de l’équipe de ESM Gonfreville-l’Orcher aux côtés de Benoît Nicolas, Rob Woestenborghs, Emilio Martin, aux palmarès impressionnants. C’est avec ces légendes du duathlon qu’il remporte cette année le titre de champion de France du Grand-Prix de D1. Il devient en 2015 l’ambassadeur du Powerman Philippines, remporte le Powerman Luxembourg et devient pour la 2ème année consécutive champion du monde à Zofingen.',
        'Gaël Le Bellec est né le 6 avril 1988 à Entrechaux, dans le Vaucluse, d’un père breton et d’une mère anglaise. C’est sur les pentes du Mt Ventoux, ce fameux géant de Provence qu’il retourner s’entraîner quand il retourne sur ses terres natales. Dès l’âge de 10 ans il partait déjà seul, courir sur les chemins de Provence...',
        'Dès son plus jeune âge, le sport est devenu un art de vivre, une nécessité pour lui. Il s’illustre dès 12 ans sur les cross nationaux et courses locales qu’il remporte pour la plupart. Quand il vient habiter en Bretagne avec ses parents c’est la passion du vélo qui le gagne. Sa première licence à 13 ans et une progression régulière l’amène en équipe de France juniors où il côtoiera de grands coureurs actuels (Tony Gallopin, Arthur Vichot…). Repéré pour ses qualités physiques à 17 ans il intégrera le pôle France de Bordeaux-Talence où il roulera aux côtés de grands noms du cyclisme sur route et piste (Mathieu Ladagnous, Vivien Brisse…). Il passera ensuite 2 années dans le club de Côtes d’Armor Cyclisme où il est aujourd’hui toujours licencié avant un passage en 2011 dans l’équipe professionnelle britannique Raleigh où il évoluera au niveau continental. Cette aventure en terre britannique lui permettra de courir sur le continent américain et de se rapprocher de ses origines anglaises, lui qui possède la double nationalité. Une belle et riche expérience pendant laquelle il côtoiera des athlètes avec des cultures et des visions du sport très intéressantes. L’approche anglo-saxonne de la  compétition et son  côté fun, relax, lui permettent aujourd’hui de relativiser et de donner au sport sa juste place dans sa   vie.',
        'Il décidera ensuite de rendre au vélo ce qu’il lui a apporté en prenant du recul sur la compétition pour devenir entraîneur de la ligue de Bretagne de cyclisme au sein de laquelle il coache les juniors et les féminines. C’est alors qu’au contact de ces jeunes sportives et sportifs il ressent le besoin d’un nouveau challenge. Après avoir repris doucement la course à pied en 2013 dans l’équipe de Marie-Pierre Toudret-Duros, l’UA Langueux, il retrouve les sous-bois lors de l’hiver suivant, remporte le titre départemental de cross et enchaîne les bons résultats. Il décide l’année suivante de tenter l’aventure en duathlon au sein du club de Pontivy triathlon. Cette année-là, les objectifs s’enchaînent et s’ajoutent les uns aux autres. Après avoir remporté le titre régional et le titre national coup sur coup il décide de s’engager sur la légendaire épreuve de Zofingen que des grands noms tels que Mark Allen ont remporté. C’est ainsi que sur le 3ème duathlon de sa carrière il devient en Suisse le premier Français à inscrire son nom au palmarès du Powerman de Zofingen au terme des 10km à pied, 150 à vélo et 30km à pied. ',
        'Une nouvelle carrière dans cette discipline du triple effort s’ouvre donc à lui. Ses débuts très prometteurs font l’effet d’une réelle surprise dans le milieu et son parcours, qui suscite l’intérêt, font de lui la nouvelle sensation du duathlon.',
        'La saison 2015 s’annonce riche en sensations pour celui qui rejoint les rangs de l’équipe de ESM Gonfreville-l’Orcher aux côtés de Benoît Nicolas, Rob Woestenborghs, Emilio Martin, aux palmarès impressionnants. C’est avec ces légendes du duathlon qu’il remporte cette année le titre de champion de France du Grand-Prix de D1. Il devient en 2015 l’ambassadeur du nouveau Powerman Philippines, premier du nom, remporte le Powerman Luxembourg et devient pour la 2ème année consécutive champion du monde à Zofingen au terme d’une course menée de bout en bout.',
      ],
    },
    en: {
      name: 'Name',
      nationality: 'Nationality',
      date_of_birth: 'Date of birth',
      size: 'Size',
      weight: 'Weight',
      awards: 'Awards',
      results: [
        'Champion du Monde longue distance 2014, 2015 and 2018',
        'Vainqueur Powerman Florides 2016',
        'Vainqueur Powerman Philippines 2016',
        'Vainqueur du Powerman Luxembourg 2015',
        '2ème du Powerman St Wendel 2016',
        '2ème du Powerman Luxembourg 2016',
        '3ème du Powerman Malaisie 2016',
        'Champion de France Longue distance 2014',
        'Champion de France par équipe 2015 (d1)',
        'Champion de Bretagne Courte distance 2014',
      ],
      bio: [
        'Gaël Le Bellec was born on the 6th of april 1988 in Entrechaux, in the south of France, from a ‘’breton’’ father and an english mother.He often returns to his native grounds to train on the steep slopes of the Mont Ventoux, the famous Provence giant. At his earliest age, he would go off running n tracks on his own. His passion for sports had already begun…',
        'He started winning fame from when he was 12 years old on local and national cross-country events which he mostly won. When he and his family moved to Brittany, west of France, Gaël decided to change sports for cycling. His first membership at 13 and a constant progress led him to be part of the French national Team at 17 where he stood alongside today’s great cyclists (Tony Gallopin, Arthur Vichot…). He then was noticed for his physical qualities and joined Bordeaux-Talence’s National cycling center where he could train with renowned track and road cyclists (mathieu Ladagnous, Vivien Brisse…). He raced the next two years as a member of the Côtes d’Armor cycling team, in which he is still registered, before signing in 2011 for the british professional Raleigh Team. This experience on british grounds, country of his origins, got him to progress on his career. It was fine and rich as he got to meet athletes from different cultures and interesting sport outlooks. The Anglo-Saxon approach on competition, fun and relaxed, allow him today to put things into perspective and to give to sport its right place in his life.',
        'Thereafter he decided to give back to cycling what it had given to him. This is how he became coach for the ‘’Brittany’’ cycling league and especially for the women and juniors. Therefore, being related to these young athletes made him long for a new challenge. Consequently he decided to slowly start up running again in 2013 in Marie-Pierre Duros’s team: UA Langueux. The incoming winter he put on his cross-country shoes, won the local races and had other promising results.The next year he set out for new adventures as he joined the duathlon Team from Pontivy. During that year, he won the regional and national championships in a row and therefore went for the legendary event of Zofingen which has been won by great names such as Mark Allen. As a result it is during the 3rd race of his career, 10km run, 150km cycling and 30km run, that he becomes in Switzerland the first Frenchman to ingrave his name into Zofingen Powerman winner’s list.A new career in this sporting discipline which blends together 3   endurance trials has opened up to him. His promising beginnings and displays are a genuine surprise in the duathlon environment, he is now the new duathlon sensation.',
        'The 2015 season has been promising and rich with sensations for this athlete who has joined the ESM Gonfreville-l’Ocher Team besides Benoit Nicolas, Rob Woestenborghs, Emilio Marin, who all have impressive ranking lists. It’s with theses duathlon legends that he won the national ‘’Grand-Prix’’. He became in 2015 the ambassador for the Powerman Philippines, he won Luxembourg’s Powerman and was for the second time in a row world champion in Zofingen.',
      ],
    },
  },
  sponsors: [
    { name: 'engie', img: '/img/g781.png' },
    { name: 'izir', img: '/img/g803.png' },
    { name: 'kasina', img: '/img/g848.png' },
    { name: 'ventoux bikes', img: '/img/g856.png' },
    { name: 'go sport', img: '/img/g1181.png' },
    { name: 'APESUD Cycling', img: '/img/g1402.png' },
    { name: 'prologo', img: '/img/g1545.png' },
    { name: 'Spirulib', img: '/img/g787.png' },
    { name: 'Colnago', img: '/img/g372.png' },
    { name: 'Kask', img: '/img/g402.png' },
    { name: 'overstims', img: '/img/g4283.png' },
    { name: 'mizuno', img: '/img/g468.png' },
    { name: 'bodemer Auto', img: '/img/g300.png' },
    { name: 'lazuli', img: '/img/g4260.png' },
    { name: 'rotor', img: '/img/path4002.png' },
    { name: 'endura', img: '/img/g410.png' },
    { name: 'mavic', img: '/img/g1173.png' },
    { name: "imprim' plast", img: '/img/g356.png' },
    { name: 'rafal', img: '/img/g862.png' },
    { name: 'Muc-Off', img: '/img/mucoff.png' },
  ],
  teams: [
    { name: 'pontivy triathlon', img: '/img/g852.png' },
    { name: 'UA langueux', img: '/img/g901.png' },
  ],
};

export default site;
